### ISSUE TITLE
Neverending "Generating" screen

### ISSUE THREAD

**Issue by nbonfire** [ModTheGungeon/ETGMod#4]
I just installed ETGMod using the newest release of ETGMod.Installer and I can get to the character select screen, and i can pull up the console, give items, etc. But when I try to enter the gungeon, it hangs on the generating screen animation.

**Comment by 0x0ade** [comment]
* What version of the installer were you using? You can find the version number in the bottom-right corner.

* Please attach your `output_log.txt` / `Player.log`. [Consult the official bug reporting info](https://steamcommunity.com/app/311690/discussions/1/371918937280841722/), but send us the log instead.

----

Note: I'm not an active ETGMod dev team member anymore, but still responsible for the MonoMod core of the installer.

**Comment by nbonfire** [comment]
i noticed theres a newer version on the site now, so I dled that and it works now. Thanks!
