### ISSUE TITLE
Command doesn't work

### ISSUE THREAD

**Issue by KookieMonsta** [ModTheGungeon/ETGMod#5]
Either it doesn't work or I'm using it incorrectly "test spawn (anything)" doesn't seem to work. I know it says test so you probably already know this, but still wanted to point it out.

**Comment by Spanospy** [comment]
In a recent update, the "test" portion was removed. Simply just use "spawn <enemy name>". This is the same case with 'give'.

**Comment by Spanospy** [comment]
In addition, you have to use the enemy's in-game names. For example, you would use "spawn bullet_kin 50" to spawn 50 bullet kins.

If you're unsure of the name of the enemy/item you want, partially type the name and press tab. (DO NOT PRESS TAB IN AN EMPTY FIELD: CONSOLE WILL BREAK AND YOU'LL HAVE TO RESTART THE GAME TO GET IT BACK.)
