### ISSUE TITLE
Console

### ISSUE THREAD

**Issue by Oraham** [ModTheGungeon/ETGMod#6]
The console just stops working after you spawn in a few things and I have to restart after every level

**Comment by Spanospy** [comment]
Do you accidentally press tab in an empty input? It's a known issue that if you try to autocomplete nothing, it'll break the console, and you'll have to restart.

**Comment by Oraham** [comment]
No. I only spawn in some things and then it stops working

On 16 Apr 2017, at 5:22 am, Spanospy <notifications@github.com<mailto:notifications@github.com>> wrote:


Do you accidentally press tab in an empty input? It's a known issue that if you try to autocomplete nothing, it'll break the console, and you'll have to restart.

**Comment by pedro2577** [comment]
same error, but, how do i fix it? it wasn't very clear

**Comment by zatherz** [comment]
@Oraham please give more info (what are you trying to spawn? what exact keys do you press to open the console, type in the command and run it?)

**Comment by Astralika** [comment]
I was coming to report the "if you press tab the console breaks" thing and instead learned about a function of the console I wasn't aware of!

At first I just thought sometimes it broke, but then I realized it was cuz I fatfingered the tab key. Which is VERY easy to do.

Good to know it's already known tho. (Hopefully it gets fixed!)

**Comment by zatherz** [comment]
A new console is in progress and it doesn't have this issue (an entire ETGMod rewrite is in progress, too).

**Comment by Astralika** [comment]
Sweet! Thanks for the rapid response, and good to know it's in the works!

**Comment by zatherz** [comment]
Fixed in rewrite
