### ISSUE TITLE
ETGMod 3.0 sources

### ISSUE THREAD

**Issue by Eugenii10** [ModTheGungeon/ETGMod#8]
Hello!
Thanks for your great work!
As I understand **"master"** branch at the https://github.com/ModTheGungeon/ETGMod have sources for the ETGMod version 3.0 (which is the default version in the *ETGMod.Installer* named as *Base*). But I cannot find many classes from the version 2.0, e.g. ETGModConsole which contains registration of all console commands. Is it intentional? Can I get full sources for my mod developing, or should I use branch **"2.0"** and install ETGMod *OLD 0.2.0*?
Thanks!

**Comment by zatherz** [comment]
Sorry for the very late reply (I didn't notice this), but I've just created a `pre-rewrite` branch which points to the last commit before I started the rewrite.
